PRAGMA defer_foreign_keys=TRUE;
CREATE TABLE users_new (
    id TEXT PRIMARY KEY,
    email TEXT UNIQUE NOT NULL,
    password TEXT NOT NULL,
    name TEXT NOT NULL,
    first_name TEXT,
    last_name TEXT,
    admission_number TEXT,
    admission_year TEXT,
    account_type TEXT DEFAULT 'ALUMNI' CHECK(account_type IN ('ALUMNI', 'FACULTY', 'STUDENT', 'STAFF')),
    role TEXT DEFAULT 'USER' CHECK(role IN ('USER', 'MODERATOR', 'ADMIN', 'SUPER_ADMIN')),
    status TEXT DEFAULT 'PENDING' CHECK(status IN ('PENDING', 'ACTIVE', 'SUSPENDED', 'DELETED')),
    is_verified INTEGER DEFAULT 0,
    profile_image TEXT,
    bio TEXT,
    headline TEXT,
    city TEXT,
    country TEXT,
    contact_email TEXT,
    contact_phone TEXT,
    linkedin_profile TEXT,
    company TEXT,
    job_title TEXT,
    graduation_year INTEGER,
    class_year INTEGER,
    is_available_as_mentor INTEGER DEFAULT 0,
    location TEXT,
    last_login TEXT,
    refresh_tokens TEXT,
    password_reset_token TEXT,
    password_reset_expires TEXT,
    email_verification_token TEXT,
    email_verification_expires TEXT,
    needs_manual_verification INTEGER DEFAULT 0,
    verification_details TEXT,
    faculty_id_card_url TEXT,
    has_premium_badge INTEGER DEFAULT 0,
    notification_settings TEXT,
    privacy_settings TEXT,
    experiences TEXT,
    educations TEXT,
    skills TEXT,
    interests TEXT,
    industry TEXT,
    created_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now')),
    updated_at TEXT NOT NULL DEFAULT (strftime('%Y-%m-%dT%H:%M:%fZ', 'now'))
);
INSERT INTO users_new SELECT * FROM users;
DROP TABLE users;
ALTER TABLE users_new RENAME TO users;
CREATE INDEX idx_users_email ON users(email);
